on:
  pull_request:
jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: deptrac-baseline-progress-action
        id: deptrac-baseline-progress-action
        uses: ./
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.deptrac-baseline-progress-action.outputs.output_message }}
          comment_tag: 'deptrac_baseline_score_comment'
          create_if_not_exists: ${{ steps.deptrac-baseline-progress-action.outputs.score_diff != 0 }} # Only create comment when baseline score changed, but always update existing comment
